server: "irc.freenode.net"
nick: "MoneroGirl"
password: "SECURE_IRC_PASSWORD"
channels:
  - "#monero"
  - "#monero-pools"

silencers:
  - "MoneroBot"

daemon:
  rpc_host: "127.0.0.1"
  rpc_port: 18081
